baseURL = 'https://blog.billbai.me/'
languageCode = "zh-Hans"                   
defaultContentLanguage = "zh"    
title = "bill bai's blog"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
hasCJKLanguage = true 

[params]
  author = "billbai"
  description = "billbai's personal blog."
  keywords = ["blog", "billbai", "technology", "life"]
  github = "https://github.com/billbai"
  DateFormat = "2006-01-02"
  defaultTheme = "auto"
  disableThemeToggle = false

  # Favicon å’Œå¤´åƒ
  favicon = "/favicon.ico"
  images = ["/avatar.png"]

  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowWordCount = true

[params.homeInfoParams]
  Title = "bill bai's blog"
  Content = "ğŸ¸ Where I share my thoughts on random stuff."

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/billbai"

[params.assets]
  disableHLJS = true        # ç¦ç”¨ Highlight.js å‰ç«¯é«˜äº®:contentReference[oaicite:44]{index=44}

[markup]
  [markup.highlight]
    codeFences = true 
    guessSyntax = true
    lineNos = true
    # noClasses = false
    style = "catppuccin-mocha"

[pagination]
  pagerSize =42

[menu]
  [[menu.main]]
    name = "ğŸ“Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "ğŸ·ï¸Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "ğŸ”Search"
    url = "/search/"
    weight = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'
